import { DiagnosisQuestion } from "@/types";

export const DIAGNOSIS_QUESTIONS: DiagnosisQuestion[] = [
  {
    id: "q1_ideal_state",
    questionText: "仕事中、理想の自分はどんな状態？",
    description: "最も惹かれるものを直感で選んでください",
    targetAxes: ["focus", "productivity", "aesthetics"],
    options: [
      {
        id: "q1_a1",
        label: "完全没頭",
        icon: "🔥",
        description: "世界が消えて、自分とアウトプットだけが存在する",
        scoreContributions: { focus: 5, productivity: 3 },
      },
      {
        id: "q1_a2",
        label: "余裕のある集中",
        icon: "☕",
        description: "コーヒー片手に、優雅にこなしている自分",
        scoreContributions: { focus: 3, aesthetics: 3, maintenance: 2 },
      },
      {
        id: "q1_a3",
        label: "高速回転モード",
        icon: "⚡",
        description: "次々とタスクを片付けていくスピード感",
        scoreContributions: { productivity: 5, focus: 2 },
      },
      {
        id: "q1_a4",
        label: "閃きの連鎖",
        icon: "💎",
        description: "インスピレーションが降りてくる、創造的な没入",
        scoreContributions: { aesthetics: 4, focus: 2, maintenance: 1 },
      },
    ],
  },
  {
    id: "q2_first_feeling",
    questionText: "デスクに座った瞬間、何を感じたい？",
    targetAxes: ["focus", "aesthetics", "ergonomics", "maintenance"],
    options: [
      {
        id: "q2_a1",
        label: "静かな高揚",
        icon: "🎯",
        description: "「さあ、やるか」——スイッチが入る感覚",
        scoreContributions: { focus: 4, maintenance: 3 },
      },
      {
        id: "q2_a2",
        label: "所有感と安心",
        icon: "👑",
        description: "「ここは俺の城だ」——自分だけの領域に包まれる",
        scoreContributions: { aesthetics: 4, ergonomics: 3 },
      },
      {
        id: "q2_a3",
        label: "ストイックな覚悟",
        icon: "⚔️",
        description: "「今日も限界を超える」——戦闘態勢に入る",
        scoreContributions: { productivity: 4, ergonomics: 3 },
      },
      {
        id: "q2_a4",
        label: "審美的な満足",
        icon: "✨",
        description: "「この空間、最高だな」——美しい環境への陶酔",
        scoreContributions: { aesthetics: 5, maintenance: 2 },
      },
    ],
  },
  {
    id: "q3_investment",
    questionText: "「投資する価値がある」と\n心から思えるのは？",
    targetAxes: ["productivity", "ergonomics", "aesthetics"],
    options: [
      {
        id: "q3_a1",
        label: "時間を生む道具",
        icon: "⏱️",
        description: "1秒の効率化に金を惜しまない。時間こそ最大の資産",
        scoreContributions: { productivity: 5, focus: 2 },
      },
      {
        id: "q3_a2",
        label: "身体への敬意",
        icon: "🛡️",
        description: "10年後の自分を守る装備。健康は最高の投資",
        scoreContributions: { ergonomics: 6, maintenance: 2 },
      },
      {
        id: "q3_a3",
        label: "五感を満たす上質さ",
        icon: "🖤",
        description: "触れて心地よい。見て美しい。使って快感がある",
        scoreContributions: { aesthetics: 5, maintenance: 2 },
      },
      {
        id: "q3_a4",
        label: "空間の格",
        icon: "🏛️",
        description: "自分のステージにふさわしい環境。空間が男の器を語る",
        scoreContributions: { aesthetics: 4, ergonomics: 2, focus: 1 },
      },
    ],
  },
  {
    id: "q4_work_aesthetic",
    questionText: "あなたの「仕事の美学」に\n最も近いのは？",
    targetAxes: ["focus", "aesthetics", "maintenance", "productivity"],
    options: [
      {
        id: "q4_a1",
        label: "引き算のミニマリズム",
        icon: "◻️",
        description: "無駄を削ぎ落とした先にある、研ぎ澄まされた空間",
        scoreContributions: { focus: 4, maintenance: 4 },
      },
      {
        id: "q4_a2",
        label: "妥協なき完璧主義",
        icon: "🔱",
        description: "全てが最高品質。一つとして手を抜かない",
        scoreContributions: { aesthetics: 5, ergonomics: 3 },
      },
      {
        id: "q4_a3",
        label: "テクノロジー武装",
        icon: "🔮",
        description: "最先端で武装する合理主義。道具が俺を強くする",
        scoreContributions: { productivity: 5, focus: 2 },
      },
      {
        id: "q4_a4",
        label: "温もりと品格の共存",
        icon: "🪵",
        description: "木の温もり、革の経年変化。時間が味方になる空間",
        scoreContributions: { aesthetics: 3, maintenance: 3, ergonomics: 2 },
      },
    ],
  },
  {
    id: "q5_end_of_day",
    questionText: "1日の終わり。\nデスクを離れるとき、\n何を感じていたい？",
    targetAxes: ["productivity", "ergonomics", "aesthetics", "maintenance"],
    options: [
      {
        id: "q5_a1",
        label: "戦い抜いた充実",
        icon: "🏆",
        description: "「今日もやり切った」——成果を積み上げた実感",
        scoreContributions: { productivity: 4, focus: 3 },
      },
      {
        id: "q5_a2",
        label: "いい環境で過ごせた幸福",
        icon: "🌙",
        description: "「身体が楽だった」——自分を大切にできた満足",
        scoreContributions: { ergonomics: 4, aesthetics: 3 },
      },
      {
        id: "q5_a3",
        label: "明日もここに来たい愛着",
        icon: "🏠",
        description: "「この空間が好きだ」——帰りたくなる場所を持つ贅沢",
        scoreContributions: { maintenance: 5, aesthetics: 2 },
      },
      {
        id: "q5_a4",
        label: "また一歩進んだ成長",
        icon: "📈",
        description: "「昨日の自分を超えた」——確かな前進の手応え",
        scoreContributions: { focus: 3, productivity: 3, maintenance: 2 },
      },
    ],
  },
  {
    id: "q6_aspiration",
    questionText: "密かに憧れる\nワークスタイルは？",
    targetAxes: ["aesthetics", "productivity", "ergonomics", "focus"],
    options: [
      {
        id: "q6_a1",
        label: "シリコンバレーCEOの機能美",
        icon: "🍎",
        description: "無駄のない、研ぎ澄まされたプロダクティビティ空間",
        scoreContributions: { productivity: 4, focus: 3, ergonomics: 1 },
      },
      {
        id: "q6_a2",
        label: "ラグジュアリーブランドCEOの書斎",
        icon: "🥃",
        description: "重厚なウォールナットデスク、革張りチェア、万年筆",
        scoreContributions: { aesthetics: 6, ergonomics: 2 },
      },
      {
        id: "q6_a3",
        label: "トップクリエイターのアトリエ",
        icon: "🎨",
        description: "感性が溢れ出す、インスピレーションの源泉",
        scoreContributions: { aesthetics: 4, focus: 2, maintenance: 2 },
      },
      {
        id: "q6_a4",
        label: "プロゲーマーの戦闘コックピット",
        icon: "🎮",
        description: "反応速度と快適性を極限まで追求した最新鋭環境",
        scoreContributions: { productivity: 4, ergonomics: 3, focus: 1 },
      },
    ],
  },
  {
    id: "q7_philosophy",
    questionText: "「男を磨く」とは、\nあなたにとって何ですか？",
    targetAxes: ["productivity", "aesthetics", "ergonomics", "maintenance"],
    options: [
      {
        id: "q7_a1",
        label: "成果で語ること",
        icon: "📊",
        description: "結果を出す環境を整える。言葉より数字。実力がすべて",
        scoreContributions: { productivity: 4, focus: 3 },
      },
      {
        id: "q7_a2",
        label: "所作を磨くこと",
        icon: "🎩",
        description: "日常の一つ一つに品格を宿す。環境が振る舞いを変える",
        scoreContributions: { aesthetics: 4, maintenance: 4 },
      },
      {
        id: "q7_a3",
        label: "身体を鍛えること",
        icon: "💪",
        description: "姿勢・健康から自分を変える。肉体は最大の資本",
        scoreContributions: { ergonomics: 6, maintenance: 2 },
      },
      {
        id: "q7_a4",
        label: "空間を整えること",
        icon: "🪞",
        description: "環境は自分を映す鏡。空間の質が、男の質を決める",
        scoreContributions: { aesthetics: 3, maintenance: 3, focus: 2 },
      },
    ],
  },
];
